sudo: false
language: java

jdk:
- oraclejdk8
# - openjdk10

# cache local Maven repo: https://docs.travis-ci.com/user/caching/
cache:
  directories:
  - $HOME/.m2/repository
#  - $HOME/.m2/wrapper
before_cache:
  - rm -rf $HOME/.m2/repository/net/oneandone/ejb-cdi-unit/

env:
- WELD_PROFILE=weld3.0
  JUNIT_PROFILE=junit4
- WELD_PROFILE=weld2.3
  JUNIT_PROFILE=junit4
- WELD_PROFILE=weld2.3
  JUNIT_PROFILE=arquillian
- WELD_PROFILE=weld1.1
  JUNIT_PROFILE=junit4


# We don't want to overtax travis (or get throttled), so we try to limit the number of combinations.
# Current strategy is, for each supported minor version of Weld, to test one early point release plus
# the most recent point release, plus some point releases which caused problems.s

script: "mvn clean install -Pbase,${WELD_PROFILE},${JUNIT_PROFILE}"

